version: 2
updates:
  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      production:
        dependency-type: production
        update-types: [minor, patch]
    ignore:
      - dependency-name: "zod"
      - dependency-name: "typescript"
      - dependency-name: "eslint"
      - dependency-name: "vite"
      - dependency-name: "@types/node"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      production:
        dependency-type: production
        update-types: [minor, patch]
    ignore:
      - dependency-name: "zod"
      - dependency-name: "typescript"
      - dependency-name: "eslint"
      - dependency-name: "vite"
      - dependency-name: "@types/node"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
